<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>OriCoopBepInEx</AssemblyName>
    <RootNamespace>OriCoopBepInEx</RootNamespace>
    <TargetFramework>net35</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OriGameDir Condition="'$(OriGameDir)' == '' and Exists('C:\Program Files (x86)\Steam\steamapps\common\Ori DE')">C:\Program Files (x86)\Steam\steamapps\common\Ori DE</OriGameDir>
    <OriGameDir Condition="'$(OriGameDir)' == '' and Exists('D:\SteamLibrary\steamapps\common\Ori DE')">D:\SteamLibrary\steamapps\common\Ori DE</OriGameDir>
    <OriGameDir Condition="'$(OriGameDir)' == ''">C:\Program Files (x86)\Steam\steamapps\common\Ori DE</OriGameDir>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="BepInEx">
      <HintPath Condition="Exists('$(OriGameDir)\BepInEx\core\BepInEx.dll')">$(OriGameDir)\BepInEx\core\BepInEx.dll</HintPath>
      <HintPath Condition="!Exists('$(OriGameDir)\BepInEx\core\BepInEx.dll') and Exists('..\..\..\API\Client\BepInEx.dll')">..\..\..\API\Client\BepInEx.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath Condition="Exists('$(OriGameDir)\oriDE_Data\Managed\0Harmony.dll')">$(OriGameDir)\oriDE_Data\Managed\0Harmony.dll</HintPath>
      <HintPath Condition="!Exists('$(OriGameDir)\oriDE_Data\Managed\0Harmony.dll') and Exists('$(OriGameDir)\BepInEx\core\0Harmony.dll')">$(OriGameDir)\BepInEx\core\0Harmony.dll</HintPath>
      <HintPath Condition="!Exists('$(OriGameDir)\oriDE_Data\Managed\0Harmony.dll') and Exists('..\..\..\API\Client\0Harmony.dll')">..\..\..\API\Client\0Harmony.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(OriGameDir)\oriDE_Data\Managed\UnityEngine.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(OriGameDir)\oriDE_Data\Managed\Assembly-CSharp.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\OriCoopShared\*.cs" Link="Shared\%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
